### ISSUE TITLE
the CircleCI Orb Registry Page link in README leads to a 404 page

### ISSUE THREAD

**Issue by tyanas** [bitcartcc/bitcartcc-orb#31]
## Orb version:

2.3.1

## What happened:

the CircleCI Orb Registry Page link in README leads to a 404 page

https://circleci.com/developer/orbs/orb/bitcart/bitcart-orb

## Expected behavior:

A visitor can see a 200-ish page. It seems https://circleci.com/developer/orbs/orb/bitcart/bitcart-shared might be the correct link

## Additional Information:

a PR will follow this in a whim

**Comment by tyanas** [comment]
https://github.com/bitcart/bitcart-orb/pull/32

**Comment by MrNaif2018** [comment]
Merged, thanks.
Just a side question: do you use our orb in your projects? It would be super cool, because it is intended to be shared between all bitcart repos but others can use some useful stuff here too

**Comment by tyanas** [comment]
Not yet, at least for now.
Just organizing things on the internet :)
